services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'      
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  redis:
  db:
  web: